-- Insert Egyptian perfume products with uploaded images
INSERT INTO products (
  id,
  name,
  slug,
  description,
  price,
  category,
  brand,
  image_url,
  gallery_images,
  sizes,
  notes,
  ingredients,
  featured,
  in_stock,
  created_at,
  updated_at
) VALUES 
(
  gen_random_uuid(),
  'Blue Vibe Aquatic',
  'blue-vibe-aquatic',
  'A refreshing aquatic fragrance inspired by the Mediterranean breeze. This modern Egyptian scent captures the essence of crystal-clear waters with marine notes and fresh citrus.',
  299.99,
  'Aquatic',
  'Attar Al-Misr',
  'https://xjrukeinsiskpwjekigc.supabase.co/storage/v1/object/public/product-images/blue%20vibe.jpg',
  ARRAY['https://xjrukeinsiskpwjekigc.supabase.co/storage/v1/object/public/product-images/blue%20vibe.jpg'],
  '{"30ml": 299.99, "50ml": 449.99, "100ml": 699.99}'::jsonb,
  '{"top": ["Sea Breeze", "Bergamot", "Lemon"], "middle": ["Marine Accord", "Jasmine", "Lily"], "base": ["White Musk", "Cedarwood", "Ambergris"]}'::jsonb,
  ARRAY['Alcohol Denat', 'Aqua', 'Parfum', 'Limonene', 'Linalool', 'Citral'],
  true,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Boje Amber Essence',
  'boje-amber-essence',
  'A rich and warm amber fragrance that embodies the golden sands of Egypt. Deep, resinous notes create a luxurious and captivating scent experience.',
  399.99,
  'Oriental',
  'Attar Al-Misr',
  'https://xjrukeinsiskpwjekigc.supabase.co/storage/v1/object/public/product-images/BOJE.jpg',
  ARRAY['https://xjrukeinsiskpwjekigc.supabase.co/storage/v1/object/public/product-images/BOJE.jpg'],
  '{"30ml": 399.99, "50ml": 599.99, "100ml": 899.99}'::jsonb,
  '{"top": ["Saffron", "Orange Blossom", "Pink Pepper"], "middle": ["Amber", "Rose", "Oud"], "base": ["Sandalwood", "Vanilla", "Musk"]}'::jsonb,
  ARRAY['Alcohol Denat', 'Parfum', 'Aqua', 'Benzyl Benzoate', 'Eugenol', 'Geraniol'],
  true,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Milka Floral Dream',
  'milka-floral-dream',
  'A delicate floral bouquet inspired by Egyptian gardens. Soft and feminine with notes of white flowers and gentle spices, perfect for everyday elegance.',
  249.99,
  'Floral',
  'Attar Al-Misr',
  'https://xjrukeinsiskpwjekigc.supabase.co/storage/v1/object/public/product-images/milka.jpg',
  ARRAY['https://xjrukeinsiskpwjekigc.supabase.co/storage/v1/object/public/product-images/milka.jpg'],
  '{"30ml": 249.99, "50ml": 379.99, "100ml": 549.99}'::jsonb,
  '{"top": ["White Tea", "Pear", "Freesia"], "middle": ["Peony", "Rose Petals", "Magnolia"], "base": ["White Musk", "Blonde Woods", "Soft Amber"]}'::jsonb,
  ARRAY['Alcohol Denat', 'Aqua', 'Parfum', 'Hydroxycitronellal', 'Hexyl Cinnamal', 'Alpha-Isomethyl Ionone'],
  false,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Pink Vibe Sunset',
  'pink-vibe-sunset',
  'A romantic and vibrant fragrance capturing the beauty of Egyptian sunsets. Sweet and fruity with a touch of oriental spices.',
  329.99,
  'Fruity',
  'Attar Al-Misr',
  'https://xjrukeinsiskpwjekigc.supabase.co/storage/v1/object/public/product-images/pink%20vibe.jpg',
  ARRAY['https://xjrukeinsiskpwjekigc.supabase.co/storage/v1/object/public/product-images/pink%20vibe.jpg'],
  '{"30ml": 329.99, "50ml": 489.99, "100ml": 729.99}'::jsonb,
  '{"top": ["Pink Grapefruit", "Raspberry", "Mandarin"], "middle": ["Rose", "Peach Blossom", "Cardamom"], "base": ["Vanilla", "Sandalwood", "Pink Musk"]}'::jsonb,
  ARRAY['Alcohol Denat', 'Parfum', 'Aqua', 'Limonene', 'Citronellol', 'Benzyl Alcohol'],
  true,
  true,
  NOW(),
  NOW()
),
(
  gen_random_uuid(),
  'Pink Vibe Evening',
  'pink-vibe-evening',
  'An intense evening version of Pink Vibe with deeper, more sensual notes. Perfect for special occasions and romantic evenings.',
  379.99,
  'Oriental',
  'Attar Al-Misr',
  'https://xjrukeinsiskpwjekigc.supabase.co/storage/v1/object/public/product-images/pink%20vibe.jpg',
  ARRAY['https://xjrukeinsiskpwjekigc.supabase.co/storage/v1/object/public/product-images/pink%20vibe.jpg'],
  '{"30ml": 379.99, "50ml": 569.99, "100ml": 849.99}'::jsonb,
  '{"top": ["Black Currant", "Pink Pepper", "Bergamot"], "middle": ["Damask Rose", "Jasmine", "Cinnamon"], "base": ["Oud", "Patchouli", "Amber"]}'::jsonb,
  ARRAY['Alcohol Denat', 'Parfum', 'Aqua', 'Benzyl Benzoate', 'Cinnamyl Alcohol', 'Eugenol'],
  false,
  true,
  NOW(),
  NOW()
);
